spring: 
   datasource: 
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: akshay
      password: akshay
      
   jpa: 
      show-sql: true
      hibernate: 
         ddl-auto: update